### PR TITLE
Add dcos cluster commands skeleton

### PR DESCRIPTION
**Pull request by bamarni**
This also moves the version to a variable in dcos_cli so that it can be used both by setup.py and the --version flag.

This is the last change I'm planning on the CLI part, next ones would be about linting / tests.

```
$ dcos
Usage: dcos [OPTIONS] COMMAND [ARGS]...

Options:
  --debug    Enable debug mode.
  --version  Print version information.
  --help     Show this message and exit.

Commands:
  cluster  Manage your DC/OS clusters.

$ dcos cluster
Debug mode is off
Usage: dcos cluster [OPTIONS] COMMAND [ARGS]...

  Manage your DC/OS clusters.

Options:
  --help  Show this message and exit.

Commands:
  attach  Attach to a cluster.
  list    List clusters.
  remove  Remove cluster(s).
  rename  Rename a cluster.
  setup   Setup a cluster.
```

### CODE REVIEW

**Comment by adamtheturtle** [comment]
Thanks @bamarni . I'm glad you're working on this project in such ha diligent manner.

Of course it is not for me to block merging, but allow me to say a personal preference.

One issue with the existing CLI is how little of it is tested, and how hard it is to test. One way to avoid that is to have no untested code. That means even testing stubs like this. The approach of "write now, test later" is what gets us into messes and if untested code is disallowed from day 1 (even this PR) then that sets a good start.

**Comment by bamarni** [comment]
This is a topic I was planning to tackle right after but we can discuss it in this PR directly.

How do you measure that the current CLI is little tested? I think it is hard to tell because we mostly have integration tests rather than unit tests.

Also, I would prefer to keep it this way and emphasize more on integration testing for this project, as this would make it easier to do TDD as you're suggesting. My point being that I don't want to maintain mocks for Marathon and all the different APIs this CLI interacts with, which would be a full-time job given the amount of people working on other teams vs. the CLI...

I would use unit tests for everything which is CLI specific or a generic library (for errors, etc.).

**Comment by adamtheturtle** [comment]
> How do you measure that the current CLI is little tested?

Perhaps this was an unfair comment. However, I've mostly been interacting with the part of the code that makes HTTP requests and handles responses. This part was not well tested.

> Also, I would prefer to keep it this way and emphasize more on integration testing for this project, as this would make it easier to do TDD as you're suggesting.

This is you call. However, I'll point out that I did not suggest TDD, but instead I suggested that we don't merge untested code.

> I would use unit tests for everything which is CLI specific or a generic library (for errors, etc.).

I was suggesting that the code merged in this PR is suited to unit tests. That doesn't mean that all code will be. Mocking Marathon does not sound sensible.

**Comment by bamarni** [comment]
@adamtheturtle : I've added tests for the current skeleton and travis integration, the build would fail if test coverage is not 100%.

**Pull request merged**
